FROM alpine:3.20

RUN apk add --no-cache \
    bash \
    busybox-extras \
    ca-certificates \
    curl \
    iproute2 \
    libcap \
    nftables \
    openrc \
    openssl \
    tar \
    unzip \
    vnstat

WORKDIR /workspace
